add docker-compose
c4dt/service-stainless pull request #113
Opened 2023-03-22 13:29 UTC by tharvik

* added a docker for webapp, and a docker file to tie all together
* build and push to docker hub
* update readme
* some cleanup

see https://github.com/c4dt/showcase/pull/289 for archive infos

2023-03-29 18:28 UTC, tharvik commented
Finally finished with this archive (:

2023-04-03 12:22 UTC, ineiti requested changes
Two nitpicks and a big request for the README.md:

1. Explain what this is, with link to the showcase
2. Show how to run the docker, w/o having to run anything else than `docker-compose up`. Add a screenshot or two.
3. Explain how to build it from scratch

2023-04-03 12:22 UTC, ineiti commented on backend/Dockerfile
> +    && apt install --no-install-recommends --yes \
Nitpick: I like my `&&` at the end of the line to have all the commands aligned. But I'm sure you have a good reason to put it at the beginning of the line - why?

2023-05-03 11:28 UTC, ineiti approved these changes

2023-05-03 11:28 UTC, merged